$(function(){
  $('#f_3').css({opacity:'0'});
  $('#f_4').css({opacity:'0'});
	$('#f_5').css({opacity:'0'});
  setTimeout(function(){
    $('#f_3').stop().animate({opacity:'1'},1000);
    $('#f_4').stop().animate({opacity:'1'},1000);
		$('#f_5').stop().animate({opacity:'1'},1000);
    $('#f_2').stop().animate({opacity:'0'},1000);
    $('#f_2').css({display:'none'});
  },8000);
});